### ISSUE TITLE
Liches of this mod in general

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/Tactics-Remix#12]
I think you upgraded all liches and added more liches.

For instance in the docks area, top left, you place some vampire lich or so.

This clashes with the Dusk NPC mod. Perhaps there could be some 
conditional trigger for that vampire lich mod so they do not appear
automatically? Perhaps a NPC that stays outside, is fearful and 
asks you to go in - but the player can decide to not ask the NPC
quite yet (NPC will just stay outside for the time being) until the
player can complete the dusk mod. That way these two mods
don't clash.

Also the lich on the south using this mass spell damage. That
one is quite hard because the weak party members die so 
quickly. Perhaps this could be changed a bit that the lich
may prefer another spell initially? 

Also, the encounter where one takes the staff of the magi
is too hard IMO. In particular the additional rune assassins
or so. Could you perhaps just add a single rune assassin
instead? That could be a special NPC related to the other
human NPC in that area, such as a sword brethren or so.

The four rune assassins are quite annoying and distract
from sniping the main bad guys there.

I like the idea of the add-on nonetheless. It's an excellent
add-on; I just wish a few things would be tweaked just a 
little bit. Many of the changes I can't use because of 
conflicts or they break the game somewhat.

**Comment by morpheus562** [comment]
I would encourage the author of Dusk to determine how best to handle this as the Lich in the Docks encounter has been present and using this building since 2009 with the original Tactics and for over a year with Tactics Remix. 

As for the liches, rune assassins, and general difficulty, I think you outlined some good examples of how to reduce the difficulty for both of those encounters for players who choose to play on difficulties less than insane. I'll take a look and see about it; however, the difficulty level is just about right for insane playthroughs.
